### ISSUE TITLE
Change mobile view on home page

### ISSUE THREAD

**Issue by Phobi-Wan-Kenobi** [Phobi-Wan-Kenobi/thurstonDevs#1]
I would like to change the way services section on the home page appears when viewing at a 575px and under screen size. 
Currently it appears like this:
![Screen Shot 2019-10-11 at 18 35 06](https://user-images.githubusercontent.com/51009269/66626845-38744f80-ec56-11e9-8e22-76fb2a9ae866.png)

I would like it to look similar to this (but obviously with the correct icons and labels in place):
![2019-10-11 18_25_47-Thurston Developments](https://user-images.githubusercontent.com/51009269/66626872-52159700-ec56-11e9-96f0-3c8d9dfe8f0b.png)

This will need to remain responsive to resize back to the current sizing when above a screen size of 575px.

**Comment by Phobi-Wan-Kenobi** [comment]
Please leave a comment if you would like to work on the issue :)

**Comment by alamariful1727** [comment]
Hello, I want to work on this issue. Can you assign me on this issue? @Phobi-Wan-Kenobi

**Comment by Phobi-Wan-Kenobi** [comment]
Sure no problem

**Comment by deividynegri** [comment]
Hey (:
I have raised a PR for this 
please have a look

**Comment by Phobi-Wan-Kenobi** [comment]
Awesome work deividynegri looks great - I have merged this now!
